### PR TITLE
Expose stringFT

### PR DESCRIPTION
**Pull request by zntfdr**
This PR: 

- exposes `gdImageStringFT` to render text on images via `SwiftGD`
- fixes a couple of typos that I've spotted in the codebase
- removes a few unused `import`s

Thank you for this great library!

### CODE REVIEW

**Comment by twostraws** [comment]
Hello! Thank you for the wonderful contribution – this looks like a really valuable feature to have 👍 

I wonder if we could perhaps look at the API a little more closely? I realize you've just exposed the internal GD function, but I think we could Swiftify it a little and make the exposed API a little nicer for developers 😀  

Let's take a look at the components we have right now:

- `func stringFT` – could this perhaps be `addText()`, `renderText()`, or similar?
- `from:` looks fine to me.
- `boundingRect:` – what is this?
- `fontList` – could this perhaps be an array of strings rather than a semi-colon-delimited strings? We can join it with semi-colons inside the function, but I wouldn't want to expose that outside the API.
- `color:` Great!
- `pointSize:` Are there plans to support other kind of sizing, or can this just be `size`?
- `angle:` We haven't used angles before in SwiftGD, but I can see this kind of thing being useful. Do you think perhaps adopting a SwiftUI-like `Angle` type would be good? That way we can let folks specify as radians or degrees. Also, is this measured from the positive X axis?
- `string:` Depending on the final function name, this might end up being the first parameter. e.g., `add(text: "Whatever"`), or `renderText("Whatever")`. I think the second option seems to fit in with the rest of the existing SwiftGD API, I think, but I'd love to hear your suggestions here.
`- Returns:` I'm not sure that an array of points is the most ergonomical approach here. Could we perhaps send back a tuple of points, or perhaps a `Rectangle`? It would be a lot safer.

**Comment by zntfdr** [comment]
Thank you for the suggestions/feedback!

> * `boundingRect:` – what is this?

Old documentation leftover. Nicely spotted! Removed, thank you!

> * `fontList` – could this perhaps be an array of strings rather than a semi-colon-delimited strings? We can join it with semi-colons inside the function, but I wouldn't want to expose that outside the API.

Done 👍🏻

> * `pointSize:` Are there plans to support other kind of sizing, or can this just be `size`?

Renamed to `size` 👍🏻 

> * `angle:` We haven't used angles before in SwiftGD, but I can see this kind of thing being useful. Do you think perhaps adopting a SwiftUI-like `Angle` type would be good? That way we can let folks specify as radians or degrees.

That was my thought, too. I didn't add an `Angle` type because I was not sure you'd be ok with adding a new type just for this API.

`Angle` type added! 👍🏻

`Geometry.swift` file is getting a little crowded:  
if it's ok by you, I'd be happy to create a `Geometry` subfolder and split all geometry types to a new file for each (this can be another PR).

> Also, is this measured from the positive X axis?

Yes, I've updated the documentation with: `The angle to rotate the rendered text from the basepoint perspective. Positive angles rotate counter-clockwise.`.

I welcome suggestions on how to improve this.

> * `string:` Depending on the final function name, this might end up being the first parameter. e.g., `add(text: "Whatever"`), or `renderText("Whatever")`. I think the second option seems to fit in with the rest of the existing SwiftGD API, I think, but I'd love to hear your suggestions here.

Agreed! 
- parameter moved to be the first
- renamed the function to `renderText`

Much more Swifty :)

>  * `- Returns:` I'm not sure that an array of points is the most ergonomical approach here. Could we perhaps send back a tuple of points, or perhaps a `Rectangle`? It would be a lot safer.

Updated to return a tuple 👍🏻 

We need to return each point separately, as they represent the four "corners" of the rendered text at any angle.

For example, if we render text at 45 degrees, we might get something like this (imagine the text within the rectangle/square):

```
     c
    /\
  /   \
d/     \ b
  \    / 
   \ /
    a
```

Where the returned tuple would be the `(a, b, c, d)` points.

**Comment by twostraws** [comment]
This is a huge improvement – thank you! I agree with the Geometry.swift split 👍

At this point only two things have me doubtful:

1. Rotating counter-clockwise rather than clockwise. The rotation direction might be normal for GD, but it's the opposite of Apple's frameworks e.g. SwiftUI. Given that our developers are more likely to come from Apple than from PHP/GD, I think we should flip the direction.
2. Tuple order in the return. Again, this is the way GD does it, but it reads odd to me. I guess everyone is different, though! If I asked you to draw a square, would you start at the bottom left? I think I'd start at the top left, then go TR, BR, BL. Or if I were drawing just dots like we have here, I think I'd go TL, TR, BL, BR. This only affects people who use access the tuple using `.0`, `.1`, etc, but I think it's still worth looking at before we plant a new release tag.

Anyway, both of those are minor and can be figured out later, so I'm going to merge this now – great work! 🙌

**Comment by twostraws** [comment]
Oh! Sorry, there was one more thing: working with fonts is always something I worry about when rendering text using GD 😅

- What happens if `fontList` is empty?
- Is there a sensible default parameter can provide here to avoid people wondering "what font can I use?"?
- What happens if the user specifies an nonexistent font?

**Comment by zntfdr** [comment]
- PR #30 splits the Geometry files
- PR #31 addresses the concerns in https://github.com/twostraws/SwiftGD/pull/29#issuecomment-899032723  

> What happens if `fontList` is empty?

No text is drawn and the returned `renderText` bounding box is all zeroes.

> Is there a sensible default parameter can provide here to avoid people wondering "what font can I use?"?

This is one of the reasons why I added the example in the documentation.
 
I'm not aware of a font that would work across platforms:  
even if there was one, I'm not sure that we could guarantee that it will work for future releases (note: I might be very wrong on this 😅).

> What happens if the user specifies an nonexistent font?

GD will use the first match in the list it can find: 
if all fonts specified are "misses" (a.k.a. GD cannot find any of them), it's the same as if the `fontList` was empty and no text will be drawn.

I'm happy to expand the `fontList` documentation mentioning this if it's ok with you.  
Currently, it says:

```
fontList: A list of font filenames to look for. The first match will be used.
```

Thank you and please let me know 😊

**Pull request merged**
